package com.delta.euler;

import java.util.ArrayList;

/**
 * Created by delta on 1/3/17.
 * <p>
 * Highly divisible triangular number
 * Problem 12
 * <p>
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
 * <p>
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * <p>
 * Let us list the factors of the first seven triangle numbers:
 * <p>
 * 1: 1
 * 3: 1,3
 * 6: 1,2,3,6
 * 10: 1,2,5,10
 * 15: 1,3,5,15
 * 21: 1,3,7,21
 * 28: 1,2,4,7,14,28
 * <p>
 * We can see that 28 is the first triangle number to have over five divisors.
 * <p>
 * What is the value of the first triangle number to have over five hundred divisors?
 */
public class HighlyDivisibleTriangularNumber {
    public static void main(String[] args) {

        ArrayList<Long> primes = new ArrayList<Long>();
        primes.add(2L);
        int counter;
        long sum = 1;
        int divisorsSum = 500;
        for (long i = 2; true; i++) {
            sum += i;
            if(isPrime(sum)){
                primes.add(sum);
                continue;
            }

        }
        //System.out.println(sum);
    }

    public static boolean isPrime(long number) {
        if (number == 0 || number == 1) {
            return false;
        } else if (number == 2 || number == 3 || number == 5 || number == 7) {
            return true;
        } else if (number % 2 == 0 || number % 3 == 0 || number % 5 == 0 || number % 7 == 0) {
            return false;
        } else {
            for (long i = 9; i < Math.sqrt(number) + 1; i++) {
                if (number % i == 0) {
                    return false;
                }
            }
        }
        return true;
    }
}
